spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/atm-challenge
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog.yaml